name: Test self-hosted

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Show info
        run: |
          echo "Hello from self-hosted runner"
          pwd
          ls -la
          cat e
